travis:
  secure:
    BINSTAR_TOKEN: IbzfGosjJIXt4veQd9KTO1IQ9XjcXwFSNgEqAdPo3d+u571/FDTDKbPiBBwj4mzQwmFTU8HZ8PDs5n+YMfWwSI0Mmm0IRGpIVr1pjTI//VDJN68z/HSw+6TU7IyZO9DicrhnPM2JBsMIXsHCRaj5k4fT8ante8H/9WQKtlp068KZvb02Ua/fhHHXY7cKJI6ZhtyMXKNknGAllPfWMoquo8xLGk2bOgmuMtjeit4Il8hv4kmVax2ezOwE5+QkPMvRZGVy9UZxjiPjy6hTRpVqBOC/xzqWvzujoE7GtShvwdEAVemyzTU0HGdE19vn6vPv8V3wjnvN0byfPNhn2wxMGLPYC50tqQXeMd6zl8tVklRAADyak8aVhqYUttlq1YxaD1/6JMxUcLkbZlH6JPZSOg8xWkV0sbOqBOg2tzHJyeUB7lP0l+mJl6oB4s2zqLjD5R2BF7FPIDPQlSHMi4fr9sX/G77P8bKB1rRLZQuSppLdy2Xpzy+k0HtLKSPe5ozOnNFj8RKUqcXSStWZFPy56BMiQNcN3tA9LZ+Z3ajfkZFbEf7qxJ8LM0qfObaUYSc1mYq0ieMbaqsR6rRDDzgGe5qDsaFtsc0iaheLrA20MbQScQiqBZE9KPtENC+maZ8ExMJon+fFmxcHzVfz6NPm3KS4X9icxQfn9+zeWnt+LuA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
