travis:
  secure:
    BINSTAR_TOKEN: FVvsxXX7M87SUOTsJvDxP1ZIxHqfxcyAfmNVMt4Urqmt7GkHsg7R7GiGdVOZb5fGACt+ISZxZ7GkF1aglxQ0Y+AbL5aNu4aiyHjyKHfN1oslOCUlpVfZQt3LaqxLqpNviPylkaUESTCDmR9XT6y8yTY5qRhprf+CnZ2C2d7diA1SIrxB0BDrkyLsU58Np6vvT9WFqooUqW+i/VYdEHbSOkRxKYTLbBnLG6D/lbtFpK4FQS7TPoWSArkE1EEcGX0kNHggc6dN15GiI2lV/Uf9qIfWzNRydtVLN4REvPoVbh1U8oYH5Fbywvus4WzMehaHDKvMcK+5CfKUfjWgeLCCJHHxgg2oMEcx3cJkQnofq3KMmq6sGknULdDgRIYgx4e7S9WXe4X0jsGaQo/yVFGtaLY/Ftgn2o+BpsecIUCX5ShsF2ZBLq2POojc1eKkCrjyEYldgm3AMvpTjqk5ZV7mLC7r6mdAJMhJV0ozV8rGtfeUrPrE1vjfJTvYXAgzUwBx6eL32whLSJHmFauWprHWOSaFaEKraxjcGU4Jw7S+9/NDosksnhLIWO4EKYpE2RpOukSqhookiZh+azjihfgIBMomdTFTLMx5KkkoWpXypLKN1tE9ghSVNnvAR2xSJWlT/nBtA9zYQFvhRadlFu1vpe7D2PTl7W+Oy23zoAaV5Ls=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
