travis:
  secure:
    BINSTAR_TOKEN: jynKWu0k+oZPOL9ih6Llxhay2X5Hh51+yXu2i69q7ZJHpzlHmRdfdB57cEE+EdRvVZ/Mms5tsuWgffW0oF8yj5/XETKDDzSPyCjZLk31T+L4SB9C+MiM84vkbsSIGJ3eg7YTZTQ95byUMi/XlkR+p6srZ9oR6U8Fl5ohwLDF8M5KLA413Ld5q76oL4TLcUz/+nt1pecz20EoTHnjJNMzLBpc9wj5w5+YJPSy9PPnw+TkZLQGd70rETWQEoD4xfvkmPv9hc+ixtiHqlSj3qYvF0IzgnbzbSLWXCNM1itNlvGVOWIofLONrkY5IxDmjv4aLPnWTzaXji0uT+uIDrRqajRFjFi8/unvjdOP6PD3VFkMH61+XLKDMZGv3+BQm+GOq4FUJ+vPGFBFk6N+oTy1oBcpNm7OiOyj7c76tDaCzoulnWeSpRKJan0Na1JKsZuuMGKd/OzvhCih7W5gZYsXDE/G1nTi/+JCSbhDuBkxqoWuI6+hNuPNbf98Li89CLVW1fHu+x8jky+8QenQO2U8/huuHc7U3ilJph8HyUSB6fq+1O4DzXVOWyh3D41FGq+utTKRlZ2gkLTi6D7h67sEryZeyO3qcnVr7W2hYCHK2lpstMYoFH+nvzWXGtakPFG96vwsOOiXvl58BAq1FuRIMx3KxSRS3Olq797Fxhckamc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
