travis:
  secure:
    BINSTAR_TOKEN: EpM+Yw4N21I11AoG3BCwpwGnD0u+LPBGFMMZo6dfad3Vt0p85FjcSmBBCBWDqd27mPq4g+RjPdXt5109q3Um0s55APXFHjlJjST1147DEIE/uRqRJLOh80xH3Hq1iH4LKgm+dmosyPWdBouKmxXl0feK1wyZVpgADs8S735kjCyP7ZGXuB1y4EDVIKDxfFCxk4/42BtaImaP8MkLXno3YxvxvHB609nk1t2E5TDg54F34qPk2yC7LezPDhTi/7p606xwWjkEdW7vr7LVayfXD6hqLOoXlR69pXqFjjWThcnGAI0e57o7zOyRIg1AgVBl+aQ6hUi1AKW7tL4/hqLaB5f1Nj1R2DUZbGvHp0bHTgGT+GlPZ9ceH96VNceubCrShqNIRbovVsEatyi04WuXBb/ktvdT82dCcP4YogUqGhv3SF/Q70IsKuaaHyc+ryb1nWgsc60klRW1M4Bguof92XmuAaHmnztAt5S9S32EVZnDWXR7IWdelbi0A8JTplDCpblRikvbtXGGMqm4peDhpyasthiKIqSzBPXp2or6c1kKVXru4z2RZ8FmRtNH2QyGbgGBMyAiP2WBU+hW7Q9FjgC6Cbpk/Gzdbcl0xslRmufeZSCKsD/EqxGNvzAys8/rBJRqJymvs14Pv2ytQoLdtGbbyI1RhseLigAnjLGn5Oc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
